backend:
  name: github
  repo: FranklyMaDear/blog
  branch: main
  site_domain: blog.franklymadear.com
  auth_type: oauth
  app_id: Ov23liPmehoZa7ZMUmuX

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Αναρτήσεις"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Φωτογραφία Εξωφύλλου", name: "cover_image", widget: "image", required: false }
      - { label: "Σύνδεσμος Βίντεο (Embed)", name: "video_url", widget: "string", required: false }
      - { label: "Κείμενο Άρθρου", name: "body", widget: "markdown" }
